"use client";

import Link from "next/link";
import { useWallet, shortAddr } from "@/lib/wallet";

export default function HomePage() {
  const { address, connect, connecting, isAdmin, contractAddress, expectedChainId, chainId } =
    useWallet();
  const wrongChain = address !== null && chainId !== null && chainId !== expectedChainId;

  return (
    <div className="space-y-12">
      <section className="grid gap-8 md:grid-cols-2 md:items-center">
        <div className="space-y-5">
          <span className="chip">on-chain · transparent · permissionless</span>
          <h1 className="font-display text-4xl font-semibold leading-tight text-forest-800 md:text-5xl">
            Book the cottage,<br />settle on the chain.
          </h1>
          <p className="text-forest-700/80 text-lg max-w-md">
            DCMS is a tiny decentralized booking system for shared cottage resources —
            cabins, saunas, fire pits. No middleman, no double-bookings, every record
            on the blockchain.
          </p>
          <div className="flex flex-wrap gap-3 pt-2">
            {address ? (
              <>
                <Link href="/resources" className="btn-primary">
                  Browse resources
                </Link>
                <Link href="/bookings" className="btn-secondary">
                  My bookings
                </Link>
              </>
            ) : (
              <button onClick={connect} disabled={connecting} className="btn-primary">
                {connecting ? "Connecting…" : "Connect wallet to start"}
              </button>
            )}
          </div>
        </div>

        <div className="card relative overflow-hidden">
          <div className="absolute -top-16 -right-16 h-48 w-48 rounded-full bg-forest-600/10" />
          <div className="absolute -bottom-12 -left-10 h-40 w-40 rounded-full bg-wood-500/10" />
          <div className="relative space-y-4">
            <div className="font-display text-xl text-forest-800">Your wallet</div>
            {address ? (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="label">Address</span>
                  <span className="font-mono text-sm">{shortAddr(address)}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="label">Chain</span>
                  <span className="font-mono text-sm">
                    {chainId} {wrongChain && <span className="text-red-600">(wrong)</span>}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="label">Role</span>
                  <span className="chip">{isAdmin ? "admin" : "user"}</span>
                </div>
                <div className="pt-2 text-xs text-forest-700/60 break-all">
                  Contract: {contractAddress}
                </div>
              </div>
            ) : (
              <div className="text-forest-700/70">
                Connect MetaMask to view your role and bookings.
              </div>
            )}
          </div>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        <FeatureCard
          title="No double bookings"
          body="Smart-contract conflict checks ensure each time slot is booked by exactly one wallet."
        />
        <FeatureCard
          title="One wallet, one vote"
          body="Propose new facilities and vote with your address — fully transparent results on-chain."
        />
        <FeatureCard
          title="Refundable cancellations"
          body="Cancel before your slot starts and the contract refunds you in the same transaction."
        />
      </section>

      <section className="space-y-4">
        <div>
          <span className="chip">Beyond the basics</span>
          <h2 className="font-display text-2xl text-forest-800 mt-2">Novelty features</h2>
        </div>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <FeatureCard
            title="Soulbound NFT receipts"
            body="Every booking mints a non-transferable ERC-5192 NFT to your wallet, with on-chain SVG art generated by the contract itself."
          />
          <FeatureCard
            title="Dynamic surge pricing"
            body="The contract scans the next 7-day window and auto-adjusts price up to 2.5× when utilization is high."
          />
          <FeatureCard
            title="On-chain reputation"
            body="Every completed booking earns a permanent reputation point — proof of trustworthy participation, written to the chain."
          />
          <FeatureCard
            title="Live event feed"
            body="The activity page subscribes directly to contract events — bookings, votes and refunds appear in real time."
          />
        </div>
      </section>
    </div>
  );
}

function FeatureCard({ title, body }: { title: string; body: string }) {
  return (
    <div className="card">
      <div className="font-display text-lg text-forest-800">{title}</div>
      <p className="mt-2 text-sm text-forest-700/80">{body}</p>
    </div>
  );
}
