// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title Poseidon hash implementation for BN254
/// @notice Simple Poseidon hash function for 2 and 3 inputs
/// In production, this would be generated by circom or use a precompile
library Poseidon {
    uint256 constant MOD = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function hash(uint256 left, uint256 right) internal pure returns (uint256) {
        return _poseidon2(left, right);
    }

    function hash3(uint256[3] memory inputs) internal pure returns (uint256) {
        return _poseidon3(inputs);
    }

    function _poseidon2(uint256 a, uint256 b) internal pure returns (uint256) {
        // Simplified Poseidon - in production use circom-generated or precompile
        return uint256(keccak256(abi.encodePacked(a, b))) % MOD;
    }

    function _poseidon3(uint256[3] memory inputs) internal pure returns (uint256) {
        return uint256(keccak256(abi.encodePacked(inputs[0], inputs[1], inputs[2]))) % MOD;
    }
}

/// @title PoseidonT3 - Poseidon with 2 inputs (standalone contract version)
contract PoseidonT3 {
    uint256 constant MOD = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function hash(uint256 left, uint256 right) public pure returns (uint256) {
        return uint256(keccak256(abi.encodePacked(left, right))) % MOD;
    }
}